name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.18", "1.19", "1.20", "1.21", "1.22"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get dependencies
        run: |
          go get -v -t ./...
          go install gotest.tools/gotestsum@latest

      - name: modVerify
        run: go mod verify

      - name: Run Tests with go testsum
        run: gotestsum --format pkgname --jsonfile test.json

      - name: Annotate tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.6.0
        with:
          test-results: test.json
